# Generated by Django 2.1.1 on 2018-09-26 23:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goddess', '0002_auto_20180911_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('location', models.CharField(max_length=25)),
                ('author', models.CharField(max_length=25)),
                ('caption', models.CharField(max_length=100)),
                ('visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
