# Generated by Django 2.1.2 on 2018-10-19 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goddess', '0006_auto_20181019_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
