# Generated by Django 2.1.3 on 2018-11-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goddess', '0007_auto_20181019_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='Anonymous', max_length=50),
            preserve_default=False,
        ),
    ]
