# Generated by Django 2.1.3 on 2018-11-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goddess', '0010_auto_20181113_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='goddess.Tag'),
        ),
    ]
